---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  entrypoint.sh: |-
    #!/bin/bash
    # Your config map for docker run kubenetes
---
apiVersion: v1
kind: Pod
metadata:
  name: katalonstudiotest01
  labels:
    name: katalonstudiotest01
    app: katest
spec: 
 containers:
  - name: katalontest01
    image: katalonstudio/katalon
    command:
      - /bin/entrypoint.sh
    volumeMounts:
    - name: configmap-volume
      mountPath: /bin/entrypoint.sh
      readOnly: true
      subPath: entrypoint.sh
    - name: source
      mountPath: /workspace
 volumes:
  - name: configmap-volume
    configMap:
      defaultMode: 0700
      name: my-configmap
  -
    emptyDir: {}
    name: source
 initContainers:
   - name: download
     image: alpine:3.7
     command: ["/bin/sh","-c"]
     args: ['apk add --no-cache git && git clone https://github.com/katalon-studio-samples/ci-samples.git /tmp/']
     volumeMounts:
      - mountPath: /tmp/
        name:  source
